### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by melflynn** [tkla/DiscordClone#3]
- [x] Not sure why you need a separate slice of state for all the ids of items. If you need this you should be able to extract it from the keys of that slice of state

**Comment by tkla** [comment]
I got the idea from https://redux.js.org/usage/structuring-reducers/normalizing-state-shape 

The approach I'm taking with it is that I'm using `allIds `as a way to enforce custom ordering if I were to implement it. 

Example, in my react component I can simply reference `this.props.servers.allIds` and render the servers in that specific order on the view. This way my react component doesn't have to handle sorting on each render and sorting will only happen on entity addition/deletion on the reducer and when the component is mounted initially. 

The caveat is that my reducers have to update both `byId` and `allIds` whenever an insertion/deletion occurs. In addition time complexity for insertion depends on how I'm sorting the items and will be O(n) for deletion. 

As of now there is no sorting and `allIds` is just in whatever order the items loaded in.

**Comment by melflynn** [comment]
Seems like you've got a plan so I'd say go for it! I'm excited to see how it plays out! I'll mark your sample state doc as complete.
