### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by tkla** [tkla/DiscordClone#6]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The elements are positioned correctly on the page
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by melflynn** [comment]
- should not prepopulate session forms with demo login
- should have a demo login button
- should conceal password on forms
- should render errors on page for login and signup
- should clear redux logger from production (you can use a conditional in your store to apply the logger middleware only if your environment is production)

**Comment by tkla** [comment]
@melflynn These should all be addressed now with the exception of the first bullet point as that is tied with a lot of back end stuff I still need to work on for navigation.

**Comment by melflynn** [comment]
Nice. Looks good - you'll just need to add a redirect for a random route. This is pretty easy and you can just make sure your '/' route is an exact route and throw a Redirect route on the end of your switch statement in app.js to handle where it should go if you put in something random

**Comment by tkla** [comment]
Forgot to update this, nonexistent path redirecting should now update path as well.

**Comment by tkla** [comment]
I'm going to close this issue for now as it's been resolved. Let me know if there are any other problems.
